<a href="https://colab.research.google.com/github/Inshalkhan/Data-Science-and-Decision-Making/blob/master/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 1: Scientific programming in Python**

**1. Create a (4x2) integer and print its attributes**

In [32]:
import numpy as np

# 4 x 2 array creation
a = np.random.random((4,2))
print(a)

# dimensionality of the array
print("Dimesnions",a.ndim)

# shape of the array
print("Shape",a.shape)

# size of the array: the number of elements it stores
print("Size",a.size)

# checking data type
print("Data Type",a.dtype)

# checking size of memory
print("Item Size",a.itemsize)

[[0.55490945 0.20252565]
 [0.37068543 0.14103033]
 [0.4209418  0.3205907 ]
 [0.73112866 0.44952052]]
Dimesnions 2
Shape (4, 2)
Size 8
Data Type float64
Item Size 8


**2. Create an array of dimension (1,10) and sort it in ascending and descending order**

In [34]:
# 1 x 10 array creation
numbers = [1, 3, 4, 2, 4, 0, 1, 3, 9, 7] 
numbers.sort() 
  
print("Ascending",numbers) 

numbers.sort(reverse = True)
print("Descending",numbers) 

Ascending [0, 1, 1, 2, 3, 3, 4, 4, 7, 9]
Descending [9, 7, 4, 4, 3, 3, 2, 1, 1, 0]


**3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]**

In [40]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
array = np.reshape(array,(3, 3))

print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**4. Stack two arrays of any size horizontally and vertically**

In [43]:
a = [[1, 2, 3],[4,5,6]]
b = [[0, 9, 3], [1, 4, 9]]

hstack = np.hstack((a, b)) 
print("Horizontal:",hstack)
print("")
vstack = np.vstack((a, b)) 
print("Vertical:",vstack)

Horizontal: [[1 2 3 0 9 3]
 [4 5 6 1 4 9]]

Vertical: [[1 2 3]
 [4 5 6]
 [0 9 3]
 [1 4 9]]


**5. Create two array of same size and find commom elements**

In [48]:
a= [1, 2, 3]
b= [2, 5 , 9]

def common(a, b): 
    a_set = set(a) 
    b_set = set(b) 
    if (a_set & b_set): 
        print(a_set & b_set) 
    else: 
        print("No common elements")

common(a,b)

{2}


**6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column**

In [59]:
import pandas as pd

matrix = [(22, 16, 23),
          (33, 7, 11),
          (44, 34, 11),
          (55, 35, 10),
          (66, 36, 13)]
 
# Create a DataFrame object
dfObj = pd.DataFrame(matrix, index=list('abcde'), columns=list('xyz'))

print (matrix)

# Get a series containing maximum value of each column
maxValuesObj = dfObj.max()
 
print('Maximum value in each column : ')
print(maxValuesObj)

# Get a series containing maximum value of each row
maxValuesObj = dfObj.max(axis=1)
print('Maximum value in each row : ')
print(maxValuesObj)


# Get a series containing minimum value of each column
minValuesObj = dfObj.min()
 
print('minimum value in each column : ')
print(minValuesObj)

# Get a series containing minimum value of each row
minValuesObj = dfObj.min(axis=1)
print('minimum value in each row : ')
print(minValuesObj)

[(22, 16, 23), (33, 7, 11), (44, 34, 11), (55, 35, 10), (66, 36, 13)]
Maximum value in each column : 
x    66
y    36
z    23
dtype: int64
Maximum value in each row : 
a    23
b    33
c    44
d    55
e    66
dtype: int64
minimum value in each column : 
x    22
y     7
z    10
dtype: int64
minimum value in each row : 
a    16
b     7
c    11
d    10
e    13
dtype: int64


**7. Create an array of size 100 and compute the mean, median, standard deviation.**

In [63]:
a = np.random.random(100)
print(a)
print("")
print("Mean",np.mean(a))
print("Median",np.median(a))
print("Standard Deviation",np.std(a))

[0.78799965 0.67957998 0.01292263 0.08327625 0.66355915 0.83515609
 0.40217472 0.89043465 0.84614606 0.89992145 0.59496529 0.37067276
 0.29149652 0.81286327 0.87970851 0.30420872 0.28155424 0.39963051
 0.96686981 0.22723512 0.85616314 0.89475942 0.68036233 0.42645847
 0.34776082 0.01769436 0.28290175 0.97600262 0.76506105 0.12808244
 0.00505258 0.9600034  0.64785617 0.44070191 0.44557786 0.52627905
 0.11045828 0.21435609 0.2692028  0.07726461 0.49298217 0.39969245
 0.75661075 0.27206824 0.16491991 0.0763311  0.05929092 0.35030493
 0.55075896 0.56047421 0.58830108 0.87362755 0.96883695 0.59893893
 0.83855678 0.22346907 0.88925543 0.29177163 0.15028542 0.13786493
 0.43325801 0.43231698 0.45689031 0.07221818 0.27242403 0.75220314
 0.07142671 0.69773678 0.99051541 0.35508453 0.26303844 0.51337372
 0.61653483 0.19558303 0.72382413 0.24837542 0.50427978 0.66961214
 0.31386992 0.22974314 0.42266514 0.76233357 0.62374077 0.56685128
 0.47475517 0.86776159 0.49053534 0.48157714 0.97459667 0.9755

**8. Normalize a 5x5 random matrix**

In [67]:
 array = [(22, 16, 23),
          (33, 7, 11),
          (44, 34, 11),
          (55, 35, 10),
          (66, 36, 13)]
 
 array = array - np.mean(array)
array = array / np.max(array)

print("Normalized Array")
print(array)

Normalized Array
[[-0.14982578 -0.30662021 -0.12369338]
 [ 0.13763066 -0.54181185 -0.43728223]
 [ 0.42508711  0.16376307 -0.43728223]
 [ 0.71254355  0.18989547 -0.46341463]
 [ 1.          0.21602787 -0.38501742]]


**9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?**

In [76]:
a = np.random.random((4,4,3))
b = np.random.random((4,4))

print("Array A")
print(a)
print("")
print("Array B")
print(b)

arr= np.outer(a, b)
print("Multiply")
print(arr)

Array A
[[[0.67749259 0.8712025  0.44587113]
  [0.96249658 0.68192987 0.11661426]
  [0.27053668 0.28596816 0.83936597]
  [0.78138738 0.16922004 0.09343891]]

 [[0.35408869 0.28421743 0.49729227]
  [0.93585344 0.67175591 0.30449586]
  [0.54713307 0.45446342 0.14725385]
  [0.01184998 0.67473342 0.9455506 ]]

 [[0.54239102 0.55661711 0.95325607]
  [0.73511577 0.06522602 0.01998715]
  [0.94764377 0.21552021 0.10298909]
  [0.00664241 0.12950965 0.79051992]]

 [[0.16709119 0.41977216 0.08194727]
  [0.36617792 0.88657742 0.36496281]
  [0.28069444 0.80510268 0.85499679]
  [0.02394969 0.3729881  0.48031072]]]

Array B
[[0.09659098 0.27269844 0.11173561 0.12249979]
 [0.84287893 0.96089782 0.8193864  0.76836488]
 [0.42527926 0.0113699  0.87638957 0.77408035]
 [0.20691153 0.75656078 0.69986485 0.82037207]]
Multiply
[[6.54396702e-02 1.84751173e-01 7.57000500e-02 8.29927027e-02
  5.71044229e-01 6.51001149e-01 5.55128212e-01 5.20561510e-01
  2.88123547e-01 7.70302176e-03 5.93747441e-01 5.24433703e-01